#!/usr/bin/env python3
"""Reproduce NEURASIGN's openly synthetic, deterministic presentation recording.

These numbers are NOT measurements, UNIVERSE participant records, or clinical
labels. Smooth, plausible feature trajectories exercise the real inference and
routing pipeline without substituting directly scripted cognitive scores.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASELINES = {
    "alex": {
        "heart_rate": {"mean": 72, "std": 8},
        "hrv": {"mean": 55, "std": 10},
        "eda": {"mean": 2.1, "std": 0.7},
        "temperature": {"mean": 33.0, "std": 0.5},
        "movement": {"mean": 0.10, "std": 0.10},
    },
    "aoi": {
        "heart_rate": {"mean": 67, "std": 8},
        "hrv": {"mean": 65, "std": 12},
        "eda": {"mean": 1.6, "std": 0.6},
        "temperature": {"mean": 32.7, "std": 0.5},
        "movement": {"mean": 0.08, "std": 0.08},
    },
}


def trajectory(worker_id: str, timestamp: float) -> float:
    if worker_id == "alex":
        return 1.65 * (1 - min(1.0, max(0.0, (timestamp - 360) / 420)))
    if timestamp < 480:
        return 0.03
    if timestamp < 1050:
        return 0.03 + 3.97 * (timestamp - 480) / 570
    if timestamp < 1440:
        return 4.0
    return 4.0 - 2.1 * min(1.0, (timestamp - 1440) / 360)


def build_fixture() -> dict:
    windows = []
    for timestamp in range(0, 1801, 10):
        for worker_id in BASELINES:
            baseline = BASELINES[worker_id]
            level = trajectory(worker_id, timestamp)
            noise = 0.04 * math.sin(timestamp / 37 + (0 if worker_id == "alex" else 2))
            shifts = {
                "heart_rate": level + noise,
                "hrv": -level + noise,
                "eda": level + noise,
                "temperature": level * 0.12,
                "movement": level * 0.12 + abs(noise),
            }
            features = {
                key: round(baseline[key]["mean"] + baseline[key]["std"] * value, 4)
                for key, value in shifts.items()
            }
            windows.append({
                "worker_id": worker_id,
                "timestamp": timestamp,
                "features": features,
                "quality": 0.92,
            })
    return {
        "metadata": {
            "kind": "fixture",
            "name": "Synthetic scenario replay",
            "description": "Deterministic synthetic signals, not UNIVERSE participant measurements. Relative states are illustrative heuristics.",
            "window_seconds": 10,
            "duration_seconds": 1800,
            "provenance": "Generated by scripts/generate_fixtures.py; no participant data used.",
            "baseline_method": "Explicit synthetic personal calibration constants, not fitted clinical baselines.",
        },
        "baselines": BASELINES,
        "windows": windows,
    }


if __name__ == "__main__":
    output = ROOT / "data" / "fixtures" / "replay.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(build_fixture(), indent=2) + "\n")
    print(f"Wrote {output.relative_to(ROOT)} (synthetic, 362 windows).")
